"""
Data Masking Utility (0/1 Point-Wise Expansion)
===============================================

This script provides an automated utility to expand the batch-level telemetry 
matrix generated by `DeepSpaceTelemetry` (`telemetry_mask_timeline.csv`) into 
a high-resolution, point-wise boolean array (0s and 1s).

It skips reading massive raw data files, and simply outputs a lightweight 
`pointwise_mask_tXXX.csv` containing the exact availability of every single 
physical data point at the requested telemetry event time.

Usage:
    julia apply_telemetry_mask.jl <run_id> <total_points> <event_row_index> <output_csv>
"""

using Pkg;
Pkg.activate(joinpath(@__DIR__, ".."), io = devnull);
Pkg.instantiate(io = devnull)
using CSV, DataFrames, TOML
# Reuse the already-loaded module when included from run_full_sim.jl (where
# `using .DeepSpaceTelemetry` exports TelemetryCore into Main); load it directly
# when running standalone.
if !isdefined(Main, :TelemetryCore)
    include(joinpath(@__DIR__, "..", "..", "src", "TelemetryCore.jl"))
end

"""
    apply_mask(run_id::String, total_points::Int, event_idx::Int, output_path::String)

Reads the 2D `telemetry_mask_timeline.csv` for the given `run_id`, locates the 
requested `event_idx` (row), expands the state machine batch IDs into a high-resolution 
point-wise boolean mask (1 for Ground availability, 0 otherwise) across `total_points`, 
and saves it to `output_path`.
"""
function apply_mask(run_id::String, total_points::Int, event_idx::Int, output_path::String)
    # 1. Locate Run Directory & Files. Physics parameters come from the run's
    # own config snapshot so the expansion stays correct after config.toml
    # edits; the project config is only a fallback for legacy runs.
    project_root = abspath(joinpath(@__DIR__, "..", ".."))
    run_dir = joinpath(project_root, "data", "runs", run_id)
    mask_path = joinpath(run_dir, "masks", "telemetry_mask_timeline.csv")
    config_path = joinpath(run_dir, "config_snapshot.toml")
    if !isfile(config_path)
        config_path = joinpath(project_root, "config.toml")
    end

    if !isfile(mask_path)
        error("Telemetry mask not found at: $mask_path")
    end
    if !isfile(config_path)
        error("No config_snapshot.toml in run dir and no project config.toml found.")
    end

    # 2. Parse Physical Parameters from Config
    cfg = TOML.parsefile(config_path)
    sample_rate = Float64(cfg["physics"]["sample_rate"])
    seg_dur = Float64(cfg["physics"]["segment_duration_sec"])
    batch_size = Int(cfg["physics"]["batch_size"])

    points_per_batch = round(Int, sample_rate * seg_dur * batch_size)
    println("Configuration loaded:")
    println("  -> Points per batch: $points_per_batch")

    # 3. Load the Telemetry Mask
    println("Loading mask timeline from: $mask_path")
    mask_df = CSV.read(mask_path, DataFrame)

    target_idx = event_idx == -1 ? nrow(mask_df) : event_idx

    if target_idx < 1 || target_idx > nrow(mask_df)
        error(
            "Event index $target_idx is out of bounds. The timeline has $(nrow(mask_df)) events.",
        )
    end

    event_row = mask_df[target_idx, :]
    event_time = event_row.SimTime
    println("Selected Telemetry Event: $event_time (Row $target_idx)")

    batch_statuses = Vector(event_row[2:end])

    # 4. Expand Batch Mask to Point-Wise Integer Array (1/0)
    println("Expanding batch masks to point-wise 0/1 array for $total_points points...")
    point_mask = zeros(Int8, total_points)

    for (batch_index, status) in enumerate(batch_statuses)
        # Status 3 means 'Ground Archive' (Successfully downlinked).
        # 0 (Future), 1 (Onboard), 2 (Link) and 4 (Lost) all stay masked:
        # a lost batch never becomes available on the ground.
        if status == 3
            start_idx = (batch_index - 1) * points_per_batch + 1
            end_idx = min(start_idx + points_per_batch - 1, total_points)

            if start_idx <= total_points
                point_mask[start_idx:end_idx] .= 1
            end
        end
    end

    # 5. Save Output
    println("Saving pointwise mask to: $output_path")
    output_df = DataFrame(Time_Index = 1:total_points, Ground_Available = point_mask)
    TelemetryCore.safe_csv_write(output_path, output_df)

    available_pts = count(x -> x == 1, point_mask)
    avail_pct = round((available_pts / total_points) * 100, digits = 2)

    println("\n=== MASK EXPANSION COMPLETE ===")
    println("Total Data Points:     $total_points")
    println("Available on Ground:   $available_pts ($avail_pct%)")
    println("Unavailable:           $(total_points - available_pts)")
end

if abspath(PROGRAM_FILE) == @__FILE__
    if length(ARGS) != 4
        println(
            "Usage: julia apply_telemetry_mask.jl <run_id> <total_points> <event_row_index> <output_csv>",
        )
        exit(1)
    end

    run_id = ARGS[1]
    total_pts = tryparse(Int, ARGS[2])
    event_idx = tryparse(Int, ARGS[3])
    out_csv = ARGS[4]
    if total_pts === nothing || event_idx === nothing
        println(
            "Error: <total_points> and <event_row_index> must be integers " *
            "(got \"$(ARGS[2])\", \"$(ARGS[3])\").",
        )
        exit(1)
    end

    apply_mask(run_id, total_pts, event_idx, out_csv)
end
