"""
    Metrology

Analysis metrics derived from a run's ground-truth event logs. The first
metric is the alert-latency curve: for a transient caught in a live batch,
how long after the event the whole look-back window of `δ` before it is on
the ground — under the realized live-FIFO / archive-LIFO doctrine and under
a counterfactual first-in, first-out drain that re-assigns the same service
completions in content order. The second is the measurement-to-ground
delay of every batch against a delivery requirement (the Definition Study
Report's 24 hours). See [`alert_latency_table`](@ref),
[`plot_alert_latency`](@ref), [`delivery_delay_table`](@ref), and
[`plot_delivery_delay`](@ref).
"""
module Metrology

using ..TelemetryCore
using ..PlotTheme
using CSV: CSV
using CairoMakie:
    CairoMakie,
    Axis,
    Figure,
    Legend,
    LineElement,
    PolyElement,
    band!,
    lines!,
    save,
    stairs!,
    text!,
    vlines!,
    with_theme,
    xlims!,
    ylims!
using DataFrames: DataFrame, nrow
using Dates: DateTime, Millisecond

"""
    quantile_sorted(values::AbstractVector{<:Real}, p::Real) -> Float64

Quantile `p ∈ [0, 1]` of an ascending-sorted vector with linear
interpolation between order statistics (the default definition of
`Statistics.quantile`). `NaN` for an empty vector.
"""
function quantile_sorted(values::AbstractVector{<:Real}, p::Real)
    n = length(values)
    n == 0 && return NaN
    n == 1 && return Float64(values[1])
    h = (n - 1) * clamp(Float64(p), 0.0, 1.0)
    lo = floor(Int, h)
    frac = h - lo
    lo + 1 >= n && return Float64(values[n])
    return Float64(values[lo+1]) + frac * (Float64(values[lo+2]) - Float64(values[lo+1]))
end

"""
    BatchDelivery

One batch in the delivery schedule: identity, content interval, generation
(finalization) instant, realized ground availability (`nothing` when the
batch never reached the ground), and the counterfactual FIFO availability
(`nothing` when the FIFO drain never reaches it within the mission).
"""
struct BatchDelivery
    name::String
    id::Int
    live::Bool
    content_epoch::DateTime
    content_end::DateTime
    generated_at::DateTime
    available_at::Union{Nothing,DateTime}
    fifo_available_at::Union{Nothing,DateTime}
end

"""
    delivery_schedule(run_dir::String) -> Vector{BatchDelivery}

Per-batch delivery bookkeeping from `events_tx.csv`, `events_rx.csv`, and
the batch metadata, sorted by content epoch. The realized availability is
the first `ingested` record of the batch. The counterfactual FIFO
availability re-assigns the realized service completions (the sorted
`ingested` instants) to the batches in content order: each completion goes
to the oldest batch that had been generated by then and is still
undelivered under FIFO — the same link, the same slots, the opposite
discipline, and no live priority. Batches without a recorded content epoch
(pre-`content_epoch` metadata) take `generation − batch span`.
"""
function delivery_schedule(run_dir::String)
    tx = CSV.read(joinpath(run_dir, "events_tx.csv"), DataFrame)
    rx_path = joinpath(run_dir, "events_rx.csv")
    rx =
        isfile(rx_path) ? CSV.read(rx_path, DataFrame) :
        DataFrame(SimTime = DateTime[], Batch = String[], Event = String[])
    physics = TelemetryCore.physics_settings(TelemetryCore.load_run_config(run_dir))
    batch_span =
        Millisecond(round(Int, physics.batch_size * physics.segment_duration_sec * 1000))
    epochs = TelemetryCore.batch_content_epochs(run_dir)

    generated = Dict{String,DateTime}()
    for r in eachrow(tx)
        r.Event == "gen" || continue
        name = String(r.Batch)
        haskey(generated, name) || (generated[name] = DateTime(r.SimTime))
    end
    ingested = Dict{String,DateTime}()
    for r in eachrow(rx)
        r.Event == "ingested" || continue
        name = String(r.Batch)
        haskey(ingested, name) || (ingested[name] = DateTime(r.SimTime))
    end

    names = sort!(collect(keys(generated)); by = TelemetryCore.batch_id)
    epoch_of(name) = get(epochs, name, generated[name] - batch_span)
    sort!(names; by = name -> (epoch_of(name), TelemetryCore.batch_id(name)))

    # Counterfactual FIFO drain over the realized service completions.
    completions = sort!(collect(values(ingested)))
    fifo = Dict{String,DateTime}()
    next = 1
    for t in completions
        # Content order is generation order, so the pool of undelivered
        # batches generated by `t` is a prefix of `names`.
        while next <= length(names) && haskey(fifo, names[next])
            next += 1
        end
        next <= length(names) || break
        generated[names[next]] <= t || continue # nothing onboard yet: slot unused
        fifo[names[next]] = t
    end

    return [
        BatchDelivery(
            name,
            TelemetryCore.batch_id(name),
            TelemetryCore.is_live_batch(name),
            epoch_of(name),
            epoch_of(name) + batch_span,
            generated[name],
            get(ingested, name, nothing),
            get(fifo, name, nothing),
        ) for name in names
    ]
end

"""
    batch_containing(schedule, t::DateTime) -> Union{Nothing,BatchDelivery}

The batch whose content interval `[content_epoch, content_end)` contains
`t`, or `nothing` (before the first batch, inside a generation gap, or after
the last).
"""
function batch_containing(schedule::Vector{BatchDelivery}, t::DateTime)
    idx = searchsortedlast(schedule, t; by = x -> x isa DateTime ? x : x.content_epoch)
    idx == 0 && return nothing
    candidate = schedule[idx]
    return t < candidate.content_end ? candidate : nothing
end

"""
    alert_latency_table(run_dir::String; lookback_hours = 72.0) -> DataFrame

Window-completeness latency curves over the look-back grid
`δ = 0, D, 2D, …` (`D` = the batch content span) up to `lookback_hours`.
Every live batch that reached the ground defines an alert whose event
instant `t_m` is the batch's content end (the moment the transient's
samples exist). The look-back window `[t_m − δ, t_m)`, together with the
alert batch itself, is complete on the ground once every batch overlapping
it has arrived; the latency is that completion instant minus `t_m` — for
the realized doctrine and for the counterfactual FIFO drain
([`delivery_schedule`](@ref)) — so `δ ≤ D` gives the delivery delay of the
live batch itself and the curve is non-decreasing in `δ`. Alerts whose window reaches before the first recorded batch, and
alerts whose window contains a batch that never arrived under either
discipline, are excluded at that `δ`; `N_Alerts` counts the contributing
alerts. Columns: `Lookback_Hours`, `N_Alerts`, and the median and 25 % /
75 % quantiles of the latency in hours for `LIFO` (realized) and `FIFO`.
"""
function alert_latency_table(run_dir::String; lookback_hours::Float64 = 72.0)
    schedule = delivery_schedule(run_dir)
    isempty(schedule) && return DataFrame()
    span = schedule[1].content_end - schedule[1].content_epoch
    steps = floor(Int, lookback_hours * 3_600_000 / span.value)
    first_epoch = schedule[1].content_epoch
    hours(ms::Millisecond) = ms.value / 3.6e6
    index_of = Dict(b.name => i for (i, b) in enumerate(schedule))

    # Per alert, the running completion instants of the window as it grows
    # one batch at a time towards the past; `nothing` once a batch that
    # never arrived enters the window.
    lifo_at = Vector{Vector{Union{Nothing,Float64}}}()
    fifo_at = Vector{Vector{Union{Nothing,Float64}}}()
    for m in schedule
        (m.live && m.available_at !== nothing && m.fifo_available_at !== nothing) ||
            continue
        t_m = m.content_end
        real = Union{Nothing,Float64}[]
        fifo = Union{Nothing,Float64}[]
        # The alert batch itself is always part of the window.
        real_max = hours(m.available_at - t_m)
        fifo_max = hours(m.fifo_available_at - t_m)
        j = index_of[m.name] - 1
        for k in 0:steps
            window_start = t_m - Millisecond(k * span.value)
            window_start < first_epoch && break
            while j >= 1 && schedule[j].content_end > window_start
                b = schedule[j]
                if b.available_at === nothing || b.fifo_available_at === nothing
                    real_max = NaN
                    fifo_max = NaN
                else
                    real_max = max(real_max, hours(b.available_at - t_m))
                    fifo_max = max(fifo_max, hours(b.fifo_available_at - t_m))
                end
                j -= 1
            end
            push!(real, isnan(real_max) ? nothing : real_max)
            push!(fifo, isnan(fifo_max) ? nothing : fifo_max)
        end
        push!(lifo_at, real)
        push!(fifo_at, fifo)
    end

    rows = NamedTuple[]
    for k in 0:steps
        lifo = Float64[]
        fifo = Float64[]
        for (real, counter) in zip(lifo_at, fifo_at)
            k + 1 <= length(real) || continue
            (real[k+1] === nothing || counter[k+1] === nothing) && continue
            push!(lifo, real[k+1])
            push!(fifo, counter[k+1])
        end
        isempty(lifo) && continue
        sort!(lifo)
        sort!(fifo)
        push!(
            rows,
            (
                Lookback_Hours = hours(Millisecond(k * span.value)),
                N_Alerts = length(lifo),
                LIFO_Median_Hours = quantile_sorted(lifo, 0.5),
                LIFO_Q25_Hours = quantile_sorted(lifo, 0.25),
                LIFO_Q75_Hours = quantile_sorted(lifo, 0.75),
                FIFO_Median_Hours = quantile_sorted(fifo, 0.5),
                FIFO_Q25_Hours = quantile_sorted(fifo, 0.25),
                FIFO_Q75_Hours = quantile_sorted(fifo, 0.75),
            ),
        )
    end
    return DataFrame(rows)
end

"""
    plot_alert_latency(run_dir::String; lookback_hours = 72.0) -> Union{Nothing,String}

Writes `<run_dir>/alert_latency.csv` ([`alert_latency_table`](@ref)) and
renders `<run_dir>/plots/alert_latency.png` (with a vector PDF twin): the
median window-completeness latency with the interquartile band against the
look-back, realized doctrine solid, counterfactual FIFO drain dashed, and
the medians at the largest tabulated look-back annotated. Returns the PNG path, or `nothing`
when the run holds no delivered live batch.
"""
function plot_alert_latency(run_dir::String; lookback_hours::Float64 = 72.0)
    table = alert_latency_table(run_dir; lookback_hours = lookback_hours)
    if isempty(table)
        @warn "[POST] No delivered live batch in $run_dir — alert-latency metric skipped."
        return nothing
    end
    TelemetryCore.safe_csv_write(joinpath(run_dir, "alert_latency.csv"), table)

    x = Float64.(table.Lookback_Hours)
    path = joinpath(run_dir, "plots", "alert_latency.png")
    mkpath(dirname(path))
    with_theme(PlotTheme.telemetry_theme()) do
        fig = Figure(size = PlotTheme.FIG_SIZE_SESSION, figure_padding = 10)
        ax = Axis(
            fig[1, 1],
            xlabel = "Look-back δ before the live event [h]",
            ylabel = "Window complete on the ground after [h]",
        )
        band!(
            ax,
            x,
            Float64.(table.FIFO_Q25_Hours),
            Float64.(table.FIFO_Q75_Hours),
            color = (PlotTheme.COLOR_ONBOARD, 0.2),
        )
        band!(
            ax,
            x,
            Float64.(table.LIFO_Q25_Hours),
            Float64.(table.LIFO_Q75_Hours),
            color = (PlotTheme.COLOR_ARCHIVE, 0.25),
        )
        lines!(
            ax,
            x,
            Float64.(table.FIFO_Median_Hours),
            color = PlotTheme.COLOR_ONBOARD,
            linestyle = :dash,
        )
        lines!(ax, x, Float64.(table.LIFO_Median_Hours), color = PlotTheme.COLOR_ARCHIVE)
        y_max = maximum(
            filter(
                isfinite,
                vcat(
                    Float64.(table.LIFO_Q75_Hours),
                    Float64.(table.FIFO_Q75_Hours),
                    Float64.(table.FIFO_Median_Hours),
                ),
            );
            init = 1.0,
        )
        xlims!(ax, 0, maximum(x) > 0 ? maximum(x) : 1.0)
        ylims!(ax, 0, 1.25 * y_max)
        last = table[end, :]
        text!(
            ax,
            0.02,
            0.97,
            text = "Waveform back to δ = $(round(last.Lookback_Hours, digits = 1)) h complete after " *
                   "$(round(last.LIFO_Median_Hours, digits = 1)) h (LIFO) vs " *
                   "$(round(last.FIFO_Median_Hours, digits = 1)) h (FIFO); medians over $(last.N_Alerts) live events",
            space = :relative,
            align = (:left, :top),
            fontsize = PlotTheme.FONTSIZE_ANNOTATION,
        )
        Legend(
            fig[0, 1],
            [
                [
                    PolyElement(color = (PlotTheme.COLOR_ARCHIVE, 0.25)),
                    LineElement(
                        color = PlotTheme.COLOR_ARCHIVE,
                        linewidth = 2 * PlotTheme.LINEWIDTH_DATA,
                    ),
                ],
                [
                    PolyElement(color = (PlotTheme.COLOR_ONBOARD, 0.2)),
                    LineElement(
                        color = PlotTheme.COLOR_ONBOARD,
                        linewidth = 2 * PlotTheme.LINEWIDTH_DATA,
                        linestyle = :dash,
                    ),
                ],
            ],
            ["Realized: live FIFO + archive LIFO", "Counterfactual: FIFO drain"];
            orientation = :horizontal,
            framevisible = false,
            backgroundcolor = :transparent,
            colgap = 28,
        )
        save(path, fig, px_per_unit = 4)
        save(splitext(path)[1] * ".pdf", fig)
    end
    @info "[POST] Alert-latency metric saved: $(relpath(path, run_dir)) and alert_latency.csv."
    return path
end

# --- Delivery delay and the 24-hour requirement ---

"""
    delivery_delay_table(run_dir::String) -> DataFrame

Measurement-to-ground delay of every generated batch: `Batch`, `Live`,
`ContentEnd`, `AvailableAt` (missing when the batch never reached the
ground), `Delay_Hours` = availability minus content end (missing when
undelivered), and `LowLatency` — whether the batch reached the ground
inside a low-latency period of the run's contact model. Built on
[`delivery_schedule`](@ref); rows sorted by content epoch.
"""
function delivery_delay_table(run_dir::String)
    schedule = delivery_schedule(run_dir)
    vis = TelemetryCore.visibility_model(TelemetryCore.load_run_config(run_dir))
    in_low_latency(t::DateTime) = begin
        w = TelemetryCore.active_window(vis, t)
        w !== nothing && w.low_latency
    end
    return DataFrame(
        Batch = [b.name for b in schedule],
        Live = [b.live for b in schedule],
        ContentEnd = [b.content_end for b in schedule],
        AvailableAt = [
            b.available_at === nothing ? missing : b.available_at for b in schedule
        ],
        Delay_Hours = [
            b.available_at === nothing ? missing :
            (b.available_at - b.content_end).value / 3.6e6 for b in schedule
        ],
        LowLatency = [
            b.available_at !== nothing && in_low_latency(b.available_at) for b in schedule
        ],
    )
end

"""
    delivery_compliance(table::DataFrame, requirement_hours::Float64) -> NamedTuple

Summary of a [`delivery_delay_table`](@ref) against a delivery requirement:
`generated`, `delivered`, `within` (delivered within `requirement_hours` of
measurement), `via_low_latency` (delivered inside a low-latency period),
`fraction_within` (of all generated batches — an undelivered batch is
non-compliant), `median_hours`, and `p95_hours` of the delivered
delays (`NaN` when nothing was delivered).
"""
function delivery_compliance(table::DataFrame, requirement_hours::Float64)
    delays = sort!(Float64[d for d in table.Delay_Hours if !ismissing(d)])
    generated = nrow(table)
    delivered = length(delays)
    within = count(<=(requirement_hours), delays)
    return (
        generated = generated,
        delivered = delivered,
        within = within,
        via_low_latency = count(table.LowLatency),
        fraction_within = generated == 0 ? NaN : within / generated,
        median_hours = quantile_sorted(delays, 0.5),
        p95_hours = quantile_sorted(delays, 0.95),
    )
end

"""
    plot_delivery_delay(run_dir::String; requirement_hours = 24.0) -> Union{Nothing,String}

Writes `<run_dir>/delivery_delay.csv` ([`delivery_delay_table`](@ref)) and
renders `<run_dir>/plots/delivery_delay.png` (vector PDF twin): the
empirical distribution of the measurement-to-ground delay — the fraction
of generated batches on the ground within a given delay, live and archive
batches as separate curves — with the requirement marked and the
compliance summary annotated. Returns the PNG path, or `nothing` when the
run generated no batch.
"""
function plot_delivery_delay(run_dir::String; requirement_hours::Float64 = 24.0)
    table = delivery_delay_table(run_dir)
    if nrow(table) == 0
        @warn "[POST] No generated batch in $run_dir — delivery-delay metric skipped."
        return nothing
    end
    TelemetryCore.safe_csv_write(joinpath(run_dir, "delivery_delay.csv"), table)
    summary = delivery_compliance(table, requirement_hours)

    # Empirical fraction of *generated* batches delivered within x hours, so
    # an undelivered batch keeps the curve below unity.
    curve(mask) = begin
        delays = sort!(Float64[d for d in table.Delay_Hours[mask] if !ismissing(d)])
        n = count(mask)
        x = vcat(0.0, delays)
        y = vcat(0.0, (1:length(delays)) ./ max(n, 1))
        x, y
    end
    x_live, y_live = curve(table.Live)
    x_arch, y_arch = curve(.!table.Live)
    x_all, y_all = curve(trues(nrow(table)))
    x_max = max(maximum(x_all; init = 0.0), requirement_hours) * 1.15

    path = joinpath(run_dir, "plots", "delivery_delay.png")
    mkpath(dirname(path))
    with_theme(PlotTheme.telemetry_theme()) do
        fig = Figure(size = PlotTheme.FIG_SIZE_SESSION, figure_padding = 10)
        ax = Axis(
            fig[1, 1],
            xlabel = "Measurement-to-ground delay [h]",
            ylabel = "Fraction of generated batches delivered",
        )
        xlims!(ax, 0, x_max)
        ylims!(ax, 0, 1.05)
        vlines!(
            ax,
            [requirement_hours],
            color = (:gray30, 0.8),
            linestyle = :dash,
            linewidth = 1.5,
        )
        stairs!(ax, x_all, y_all, color = :gray40, linewidth = PlotTheme.LINEWIDTH_DATA)
        count(table.Live) > 0 && stairs!(ax, x_live, y_live, color = PlotTheme.COLOR_LIVE)
        count(.!table.Live) > 0 && stairs!(ax, x_arch, y_arch, color = PlotTheme.COLOR_ARCHIVE)
        # Bottom-right corner: the curves occupy the upper-left triangle, so
        # three short lines here clear the data and the requirement label.
        text!(
            ax,
            0.98,
            0.06,
            text = "$(round(100 * summary.fraction_within, digits = 1)) % of $(summary.generated) batches within " *
                   "$(round(requirement_hours, digits = 1)) h\n" *
                   "Median $(round(summary.median_hours, digits = 1)) h, " *
                   "95th percentile $(round(summary.p95_hours, digits = 1)) h\n" *
                   "$(summary.generated - summary.delivered) undelivered at run end" *
                   (
                       summary.via_low_latency > 0 ?
                       "\n$(summary.via_low_latency) delivered in low-latency periods" : ""
                   ),
            space = :relative,
            align = (:right, :bottom),
            justification = :right,
            fontsize = PlotTheme.FONTSIZE_ANNOTATION,
        )
        text!(
            ax,
            requirement_hours,
            0.05,
            text = "Requirement: $(round(requirement_hours, digits = 1)) h",
            align = (:left, :bottom),
            offset = (4, 0),
            fontsize = PlotTheme.FONTSIZE_ANNOTATION,
            color = :gray30,
        )
        Legend(
            fig[0, 1],
            [
                LineElement(color = :gray40, linewidth = 2 * PlotTheme.LINEWIDTH_DATA),
                LineElement(
                    color = PlotTheme.COLOR_LIVE,
                    linewidth = 2 * PlotTheme.LINEWIDTH_DATA,
                ),
                LineElement(
                    color = PlotTheme.COLOR_ARCHIVE,
                    linewidth = 2 * PlotTheme.LINEWIDTH_DATA,
                ),
            ],
            ["All batches", "Live", "Archive"];
            orientation = :horizontal,
            framevisible = false,
            backgroundcolor = :transparent,
            colgap = 28,
        )
        save(path, fig, px_per_unit = 4)
        save(splitext(path)[1] * ".pdf", fig)
    end
    @info "[POST] Delivery-delay metric saved: $(relpath(path, run_dir)) and delivery_delay.csv ($(round(100 * summary.fraction_within, digits = 1)) % within $(requirement_hours) h)."
    return path
end

end # module Metrology
