"""
    VirtualInstrument

Science-payload data source: amplitude-calibrated synthetic LISA strain via
windowed overlap-add FFT synthesis against the sky-averaged LISA sensitivity
of Robson, Cornish & Liu (2019), or gapless segmented ingestion of an
external CSV time series.
"""
module VirtualInstrument

using ..TelemetryCore
using CSV: CSV
using DataFrames: DataFrames, DataFrame
using Dates: Dates, DateTime, Second
using AbstractFFTs: AbstractFFTs, Plan
using FFTW: FFTW, plan_irfft, rfftfreq
using LinearAlgebra: LinearAlgebra, mul!
using Random: Random, AbstractRNG, Xoshiro, randn!

"""
    InstrumentState

Maintains the state of the satellite's scientific payload. Can generate synthetic
LISA strain noise (instrument sensitivity plus the galactic-confusion
foreground, [`lisa_noise_psd`](@ref)) or ingest an externally provided
continuous 1D time-series CSV array.

Synthetic strain is generated by a windowed overlap-add (WOLA) scheme:
amplitude-calibrated colored-noise blocks of `2N` samples (`N` = samples per
segment) are shaped with a periodic sqrt-Hann window and summed at 50% overlap.
The squared window tiles to exactly 1, so the emitted stream is stationary,
continuous across segment boundaries, and reproduces the sky-averaged LISA
sensitivity with the correct absolute amplitude (spectral content below
`1/(2·segment_duration_sec)` Hz is not representable at this block length — increase
`segment_duration_sec` for low-frequency fidelity). The constructor keywords
`confusion_observation_years` (0.5, 1.0, 2.0, or 4.0) select the confusion
fit and `noise_f_min_hz` the lower edge of the synthesized band: bins below
it, the DC bin included, carry no power, so the model is never evaluated
outside its domain.

The amplitude spectrum is stored in `Float64`: raw LISA PSD values (~1e-40)
underflow into `Float32` subnormals.

All stochastic draws (noise phases) come from the instrument's
own `rng` (any `Random.AbstractRNG`; default `Xoshiro(0)`), seeded via the constructor keyword —
the stream is fully reproducible from `simulation.rng_seed` and independent of
the global RNG and of other simulation components.

The struct is deliberately named differently from its parent module: an exported
struct sharing the module's name shadows the module binding in downstream
`using` scopes, breaking qualified access (`VirtualInstrument.next_segment!`).
"""
mutable struct InstrumentState{R<:Random.AbstractRNG}
    last_t::DateTime
    id_counter::Int
    sample_rate::Float64
    segment_duration_sec::Float64

    use_external::Bool
    noise_amp::Vector{Float64}   # scaled amplitude spectrum of one 2N synthesis block
    window::Vector{Float64}      # periodic sqrt-Hann window of length 2N
    carry::Vector{Float64}       # overlap-add tail carried into the next segment
    # Cached inverse-FFT plan and reusable draw/output buffers of the
    # synthesis hot path. The plan field is annotated with the abstract
    # `AbstractFFTs.Plan` — the concrete FFTW plan type is an implementation
    # detail, and the single dynamic dispatch per block is negligible against
    # the transform itself.
    irfft_plan::Plan{ComplexF64}
    z_buffer::Vector{ComplexF64}     # spectral draw, refilled per block
    block_buffer::Vector{Float64}    # windowed block, rewritten per block
    ext_data::Vector{Float32}
    ext_index::Int
    rng::R

    function InstrumentState(
        start_t::DateTime,
        sample_rate::Float64,
        segment_duration_sec::Float64,
        data_source::String,
        ext_path::String;
        rng::Random.AbstractRNG = Xoshiro(0),
        confusion_observation_years::Real = 1.0,
        noise_f_min_hz::Real = 1e-5,
    )
        n_samples = round(Int, sample_rate * segment_duration_sec)
        haskey(CONFUSION_FITS, Float64(confusion_observation_years)) || throw(
            ArgumentError(
                "confusion_observation_years must be one of 0.5, 1.0, 2.0, 4.0 (got $confusion_observation_years).",
            ),
        )
        noise_f_min_hz > 0 ||
            throw(ArgumentError("noise_f_min_hz must be > 0 (got $noise_f_min_hz)."))
        if data_source == "external"
            # Resolve relative paths against the project root (same rule as
            # validate_config) so runs work from any working directory.
            resolved =
                isabspath(ext_path) ? ext_path :
                joinpath(TelemetryCore.PROJECT_ROOT, ext_path)
            if !isfile(resolved)
                TelemetryCore.config_error(
                    "[CONFIG] External data source specified but file not found at: $resolved",
                )
            end
            df = try
                CSV.read(resolved, DataFrame)
            catch e
                TelemetryCore.config_error(
                    "[CONFIG] Failed to parse external data CSV at $resolved: $(sprint(showerror, e))",
                )
            end
            isempty(df) && TelemetryCore.config_error(
                "[CONFIG] External data CSV at $resolved contains no rows.",
            )
            # Assume single column or column named 'Amplitude'
            ext_col = hasproperty(df, :Amplitude) ? df.Amplitude : df[:, 1]
            ext_data = try
                Float32.(ext_col)
            catch
                TelemetryCore.config_error(
                    "[CONFIG] External data column in $resolved must be numeric with no missing values (got eltype $(eltype(ext_col))).",
                )
            end
            new{typeof(rng)}(
                start_t,
                1,
                sample_rate,
                segment_duration_sec,
                true,
                Float64[],
                Float64[],
                Float64[],
                plan_irfft(ComplexF64[0.0im], 1),
                ComplexF64[],
                Float64[],
                ext_data,
                1,
                rng,
            )
        else
            block_len = 2 * n_samples
            freqs = rfftfreq(block_len, sample_rate)
            # FFTW's unnormalized rfft convention: E|X_k|^2 = S(f_k)·fs·M/2
            # reproduces the one-sided PSD S after Julia's normalized irfft.
            # Bins below `noise_f_min_hz` (the DC bin included) carry no power:
            # the sensitivity model is not evaluated outside its band.
            noise_amp = [
                f < noise_f_min_hz ? 0.0 :
                sqrt(
                    lisa_noise_psd(f; observation_years = confusion_observation_years) *
                    sample_rate *
                    block_len / 2,
                ) for f in freqs
            ]
            # Periodic sqrt-Hann: w²(n) + w²(n + M/2) = 1, so 50%-overlapped
            # independent blocks sum to a stationary stream with exact variance.
            window = [sqrt(0.5 * (1 - cos(2π * (n - 1) / block_len))) for n in 1:block_len]
            irfft_plan = plan_irfft(Vector{ComplexF64}(undef, length(noise_amp)), block_len)
            z_buffer = Vector{ComplexF64}(undef, length(noise_amp))
            block_buffer = Vector{Float64}(undef, block_len)
            # Warm-up block so the very first segment is already stationary
            synth_windowed_block!(
                block_buffer,
                z_buffer,
                irfft_plan,
                rng,
                noise_amp,
                window,
            )
            carry = block_buffer[(n_samples+1):end]
            new{typeof(rng)}(
                start_t,
                1,
                sample_rate,
                segment_duration_sec,
                false,
                noise_amp,
                window,
                carry,
                irfft_plan,
                z_buffer,
                block_buffer,
                Float32[],
                1,
                rng,
            )
        end
    end
end

"""
    synth_windowed_block!(block, z, irfft_plan, rng, noise_amp, window)

In-place core of [`synth_windowed_block`](@ref): draws the spectral
realization into `z`, applies the cached `irfft_plan`, and writes the
windowed block into `block`. Allocation-free apart from the transform's
internal workspace; the RNG draw order is identical to the allocating form,
so seeded streams are unchanged.
"""
function synth_windowed_block!(
    block::Vector{Float64},
    z::Vector{ComplexF64},
    irfft_plan::Plan{ComplexF64},
    rng::AbstractRNG,
    noise_amp::Vector{Float64},
    window::Vector{Float64},
)
    randn!(rng, z)
    z[1] = 0.0 + 0.0im               # zero-mean stream: no DC power
    z[end] = sqrt(2) * real(z[end])  # Nyquist bin of a real signal is real
    z .*= noise_amp
    mul!(block, irfft_plan, z)
    block .*= window
    return block
end

"""
    synth_windowed_block(rng::AbstractRNG, noise_amp::Vector{Float64}, window::Vector{Float64})

Synthesizes one sqrt-Hann-windowed block of amplitude-calibrated colored noise
of `length(window)` samples from the scaled amplitude spectrum `noise_amp`
(see [`InstrumentState`](@ref)), drawing phases from `rng`. The DC bin is
zeroed and the Nyquist bin is forced real, as required for a real-valued
signal. Allocating convenience form of [`synth_windowed_block!`](@ref).
"""
function synth_windowed_block(
    rng::AbstractRNG,
    noise_amp::Vector{Float64},
    window::Vector{Float64},
)
    block = Vector{Float64}(undef, length(window))
    z = Vector{ComplexF64}(undef, length(noise_amp))
    plan = plan_irfft(z, length(window))
    return synth_windowed_block!(block, z, plan, rng, noise_amp, window)
end

"""
    CONFUSION_FITS

Galactic-confusion fit parameters `(α, β, κ, γ, f_k)` of Robson, Cornish &
Liu (2019), Table 1, keyed by the observation time in years (`0.5`, `1.0`,
`2.0`, `4.0`); `f_k` in Hz.
"""
const CONFUSION_FITS = Dict{Float64,NTuple{5,Float64}}(
    0.5 => (0.133, 243.0, 482.0, 917.0, 0.00258),
    1.0 => (0.171, 292.0, 1020.0, 1680.0, 0.00215),
    2.0 => (0.165, 299.0, 611.0, 1340.0, 0.00173),
    4.0 => (0.138, -221.0, 521.0, 1680.0, 0.00113),
)

"""
    CONFUSION_AMPLITUDE

Amplitude `A = 9 × 10⁻⁴⁵ Hz⁻¹` of the galactic-confusion fit (Robson,
Cornish & Liu 2019, Eq. 14).
"""
const CONFUSION_AMPLITUDE = 9e-45

"""
    OMS_NOISE_AMPLITUDE

Amplitude `1.5 × 10⁻¹¹ m Hz⁻¹ᐟ²` of the optical-metrology-system
displacement noise `P_OMS(f)` in Robson, Cornish & Liu (2019), Eq. 1.
"""
const OMS_NOISE_AMPLITUDE = 1.5e-11

"""
    OMS_NOISE_KNEE_HZ

Knee frequency `2 mHz` of the low-frequency rise `(1 + (f_knee / f)⁴)` of
`P_OMS(f)` [Hz].
"""
const OMS_NOISE_KNEE_HZ = 2e-3

"""
    ACCELERATION_NOISE_AMPLITUDE

Amplitude `3 × 10⁻¹⁵ m s⁻² Hz⁻¹ᐟ²` of the test-mass acceleration noise
`P_acc(f)` in Robson, Cornish & Liu (2019), Eq. 1.
"""
const ACCELERATION_NOISE_AMPLITUDE = 3e-15

"""
    ACCELERATION_NOISE_LOW_KNEE_HZ

Knee frequency `0.4 mHz` of the low-frequency rise `(1 + (f_knee / f)²)` of
`P_acc(f)` [Hz].
"""
const ACCELERATION_NOISE_LOW_KNEE_HZ = 0.4e-3

"""
    ACCELERATION_NOISE_HIGH_KNEE_HZ

Knee frequency `8 mHz` of the high-frequency rise `(1 + (f / f_knee)⁴)` of
`P_acc(f)` [Hz].
"""
const ACCELERATION_NOISE_HIGH_KNEE_HZ = 8e-3

"""
    RESPONSE_CORRECTION_COEFFICIENT

Dimensionless coefficient `0.6` of the high-frequency correction
`1 + 0.6 (f / f*)²` to the sky-averaged response in Robson, Cornish & Liu
(2019), Eq. 1.
"""
const RESPONSE_CORRECTION_COEFFICIENT = 0.6

"""
    lisa_instrument_psd(f) -> Float64

Sky- and polarization-averaged LISA instrument sensitivity `S_n(f)` [Hz⁻¹]
at frequency `f` [Hz], Robson, Cornish & Liu (2019) Eq. 1:

    S_n(f) = 10 / (3 L²) · [P_OMS(f) + 2 (1 + cos²(f/f*)) P_acc(f) / (2π f)⁴] · [1 + 0.6 (f/f*)²]

with `P_OMS = (1.5 × 10⁻¹¹)² (1 + (2 mHz / f)⁴) m² Hz⁻¹`,
`P_acc = (3 × 10⁻¹⁵)² (1 + (0.4 mHz / f)²) (1 + (f / 8 mHz)⁴) m² s⁻⁴ Hz⁻¹`
(the constants [`OMS_NOISE_AMPLITUDE`](@ref), [`OMS_NOISE_KNEE_HZ`](@ref),
[`ACCELERATION_NOISE_AMPLITUDE`](@ref),
[`ACCELERATION_NOISE_LOW_KNEE_HZ`](@ref),
[`ACCELERATION_NOISE_HIGH_KNEE_HZ`](@ref), and
[`RESPONSE_CORRECTION_COEFFICIENT`](@ref)), `L = 2.5 × 10⁹ m`, and
`f* = c / (2π L)`. This is the noise PSD divided by
the sky-averaged response, the quantity a strain stream is whitened
against. Returns `Inf` for `f ≤ 0`.
"""
function lisa_instrument_psd(f)
    f = Float64(f)
    f <= 0.0 && return Inf
    L = TelemetryCore.L_ARM
    f_star = TelemetryCore.F_STAR
    p_oms = OMS_NOISE_AMPLITUDE^2 * (1 + (OMS_NOISE_KNEE_HZ / f)^4)
    p_acc =
        ACCELERATION_NOISE_AMPLITUDE^2 *
        (1 + (ACCELERATION_NOISE_LOW_KNEE_HZ / f)^2) *
        (1 + (f / ACCELERATION_NOISE_HIGH_KNEE_HZ)^4)
    return (10 / (3 * L^2)) *
           (p_oms + 2 * (1 + cos(f / f_star)^2) * p_acc / (2π * f)^4) *
           (1 + RESPONSE_CORRECTION_COEFFICIENT * (f / f_star)^2)
end

"""
    lisa_confusion_psd(f, observation_years = 1.0) -> Float64

Unresolved galactic-binary confusion foreground `S_c(f)` [Hz⁻¹] at
frequency `f` [Hz], Robson, Cornish & Liu (2019) Eq. 14:

    S_c(f) = A f^(-7/3) exp(-f^α + β f sin(κ f)) [1 + tanh(γ (f_k − f))]

with `A` = [`CONFUSION_AMPLITUDE`](@ref) and `(α, β, κ, γ, f_k)` from
[`CONFUSION_FITS`](@ref) for `observation_years` (one of 0.5, 1.0, 2.0,
4.0; `ArgumentError` otherwise). Returns `Inf` for `f ≤ 0`.

The product is evaluated in log space with
`log(1 + tanh(x)) = log 2 − softplus(−2x)`: far above the knee `f_k` the
cutoff factor underflows to zero while `exp(β f sin(κ f))` can overflow,
and the direct product would give `NaN` where the foreground is zero.
"""
function lisa_confusion_psd(f, observation_years::Real = 1.0)
    fit = get(CONFUSION_FITS, Float64(observation_years), nothing)
    fit === nothing && throw(
        ArgumentError(
            "confusion_observation_years must be one of 0.5, 1.0, 2.0, 4.0 (got $observation_years).",
        ),
    )
    f = Float64(f)
    f <= 0.0 && return Inf
    α, β, κ, γ, f_k = fit
    y = -2 * γ * (f_k - f)
    softplus = max(y, 0.0) + log1p(exp(-abs(y)))
    log_s =
        log(CONFUSION_AMPLITUDE) - (7 / 3) * log(f) - f^α + β * f * sin(κ * f) + log(2.0) -
        softplus
    return exp(log_s)
end

"""
    lisa_noise_psd(f; observation_years = 1.0) -> Float64

Sky-averaged LISA sensitivity [Hz⁻¹] at frequency `f` [Hz]: the instrument
term [`lisa_instrument_psd`](@ref) plus the galactic-confusion foreground
[`lisa_confusion_psd`](@ref) of the fit for `observation_years`. It is the
noise PSD divided by the sky- and polarization-averaged response (Robson,
Cornish & Liu 2019, Eqs. 1 and 14), the quantity the downstream classifier
whitens against, and the synthesis reproduces it at the correct absolute
level. Returns `Inf` for `f ≤ 0`; the synthesis zeroes the DC bin and every
bin below `noise_f_min_hz`, so no floor value can enter a stream.
"""
function lisa_noise_psd(f; observation_years::Real = 1.0)
    return lisa_instrument_psd(f) + lisa_confusion_psd(f, observation_years)
end

"""
    next_segment!(vi::InstrumentState)

Produces the next temporal segment of science data, either sliced from the
external array or synthesized as calibrated noise. Synthetic
segments are phase-continuous across calls: each segment is the sum of the
previous block's overlap-add tail and the head of a freshly synthesized
windowed block (see [`InstrumentState`](@ref)).
"""
function next_segment!(vi::InstrumentState)
    n_samples = round(Int, vi.sample_rate * vi.segment_duration_sec)

    if vi.use_external
        # Slice from external array
        end_idx = min(vi.ext_index + n_samples - 1, length(vi.ext_data))
        if vi.ext_index + n_samples - 1 > length(vi.ext_data)
            @warn "[INSTRUMENT] External data exhausted at segment $(vi.id_counter) " *
                  "(sample $(vi.ext_index) of $(length(vi.ext_data))): padding with zeros " *
                  "from here on. Provide a longer series or shorten the mission." maxlog = 1
        end
        if vi.ext_index > length(vi.ext_data)
            # Pad with zeros if we run out of external data
            data = zeros(Float32, n_samples)
        else
            data = vi.ext_data[vi.ext_index:end_idx]
            # Pad if slice is too short
            if length(data) < n_samples
                append!(data, zeros(Float32, n_samples - length(data)))
            end
        end
        vi.ext_index += n_samples
    else
        block = synth_windowed_block!(
            vi.block_buffer,
            vi.z_buffer,
            vi.irfft_plan,
            vi.rng,
            vi.noise_amp,
            vi.window,
        )
        data = Float32.(vi.carry .+ view(block, 1:n_samples))
        copyto!(vi.carry, 1, block, n_samples + 1, n_samples)
    end

    seg = TelemetryCore.DataSegment(vi.id_counter, vi.last_t, data)
    vi.last_t += Second(round(Int, vi.segment_duration_sec))
    vi.id_counter += 1
    return seg
end

end # module VirtualInstrument
