"""
    VirtualInstrument

Science-payload data source: amplitude-calibrated synthetic LISA strain via
windowed overlap-add FFT synthesis against the analytic one-sided noise PSD,
or gapless chunked ingestion of an external CSV time series.
"""
module VirtualInstrument

using ..TelemetryCore
using CSV: CSV
using DataFrames: DataFrames, DataFrame
using Dates: Dates, DateTime, Second
using FFTW: FFTW, irfft, rfftfreq
using Random: Random, AbstractRNG, Xoshiro

export InstrumentState, lisa_noise_psd, next_segment!

"""
    InstrumentState

Maintains the state of the satellite's scientific payload. Can generate synthetic
LISA gravitational wave noise (Optical Metrology + Acceleration) or ingest an
externally provided continuous 1D time-series CSV array.

Synthetic strain is generated by a windowed overlap-add (WOLA) scheme:
amplitude-calibrated colored-noise blocks of `2N` samples (`N` = samples per
segment) are shaped with a periodic sqrt-Hann window and summed at 50% overlap.
The squared window tiles to exactly 1, so the emitted stream is stationary,
continuous across segment boundaries, and reproduces the one-sided LISA PSD
with the correct absolute amplitude (spectral content below `1/(2·seg_dur)` Hz
is not representable at this block length — increase `segment_duration_sec` for
low-frequency fidelity).

The amplitude spectrum is stored in `Float64`: raw LISA PSD values (~1e-40)
underflow into `Float32` subnormals.

All stochastic draws (noise phases, signal flags) come from the instrument's
own `rng` (any `Random.AbstractRNG`; default `Xoshiro(0)`), seeded via the constructor keyword —
the stream is fully reproducible from `simulation.rng_seed` and independent of
the global RNG and of other simulation components.

The struct is deliberately named differently from its parent module: an exported
struct sharing the module's name shadows the module binding in downstream
`using` scopes, breaking qualified access (`VirtualInstrument.next_segment!`).
"""
mutable struct InstrumentState
    last_t::DateTime
    id_counter::Int
    sample_rate::Float64
    seg_dur::Float64

    use_external::Bool
    noise_amp::Vector{Float64}   # scaled amplitude spectrum of one 2N synthesis block
    window::Vector{Float64}      # periodic sqrt-Hann window of length 2N
    carry::Vector{Float64}       # overlap-add tail carried into the next segment
    ext_data::Vector{Float32}
    ext_index::Int
    rng::Random.AbstractRNG
    signal_injection_probability::Float64

    function InstrumentState(
        start_t::DateTime,
        sample_rate::Float64,
        seg_dur::Float64,
        data_source::String,
        ext_path::String;
        rng::Random.AbstractRNG = Xoshiro(0),
        signal_injection_probability::Float64 = 0.02,
    )
        n_samples = round(Int, sample_rate * seg_dur)
        if data_source == "external"
            # Resolve relative paths against the project root (same rule as
            # validate_config) so runs work from any working directory.
            resolved =
                isabspath(ext_path) ? ext_path :
                joinpath(TelemetryCore.PROJECT_ROOT, ext_path)
            if !isfile(resolved)
                error("External data source specified but file not found at: $resolved")
            end
            df = try
                CSV.read(resolved, DataFrame)
            catch e
                error(
                    "[CONFIG] Failed to parse external data CSV at $resolved: $(sprint(showerror, e))",
                )
            end
            isempty(df) &&
                error("[CONFIG] External data CSV at $resolved contains no rows.")
            # Assume single column or column named 'Amplitude'
            ext_col = hasproperty(df, :Amplitude) ? df.Amplitude : df[:, 1]
            ext_data = try
                Float32.(ext_col)
            catch
                error(
                    "[CONFIG] External data column in $resolved must be numeric with no missing values (got eltype $(eltype(ext_col))).",
                )
            end
            new(
                start_t,
                1,
                sample_rate,
                seg_dur,
                true,
                Float64[],
                Float64[],
                Float64[],
                ext_data,
                1,
                rng,
                signal_injection_probability,
            )
        else
            block_len = 2 * n_samples
            freqs = rfftfreq(block_len, sample_rate)
            # FFTW's unnormalized rfft convention: E|X_k|^2 = S(f_k)·fs·M/2
            # reproduces the one-sided PSD S after Julia's normalized irfft.
            noise_amp =
                [sqrt(lisa_noise_psd(f) * sample_rate * block_len / 2) for f in freqs]
            # Periodic sqrt-Hann: w²(n) + w²(n + M/2) = 1, so 50%-overlapped
            # independent blocks sum to a stationary stream with exact variance.
            window = [sqrt(0.5 * (1 - cos(2π * (n - 1) / block_len))) for n in 1:block_len]
            # Warm-up block so the very first segment is already stationary
            carry = synth_windowed_block(rng, noise_amp, window)[(n_samples+1):end]
            new(
                start_t,
                1,
                sample_rate,
                seg_dur,
                false,
                noise_amp,
                window,
                carry,
                Float32[],
                1,
                rng,
                signal_injection_probability,
            )
        end
    end
end

"""
    synth_windowed_block(rng::AbstractRNG, noise_amp::Vector{Float64}, window::Vector{Float64})

Synthesizes one sqrt-Hann-windowed block of amplitude-calibrated colored noise
of `length(window)` samples from the scaled amplitude spectrum `noise_amp`
(see [`InstrumentState`](@ref)), drawing phases from `rng`. The DC bin is
zeroed and the Nyquist bin is forced real, as required for a real-valued
signal.
"""
function synth_windowed_block(
    rng::AbstractRNG,
    noise_amp::Vector{Float64},
    window::Vector{Float64},
)
    z = randn(rng, ComplexF64, length(noise_amp))
    z[1] = 0.0 + 0.0im               # zero-mean stream: no DC power
    z[end] = sqrt(2) * real(z[end])  # Nyquist bin of a real signal is real
    block = irfft(z .* noise_amp, length(window))
    block .*= window
    return block
end

"""
    lisa_noise_psd(f)

Analytic one-sided power spectral density of the LISA strain noise at
frequency `f` [Hz], comprising three components: Optical Metrology System
(shot/readout) noise, test-mass acceleration noise, and the unresolved
galactic-binary confusion foreground. Returns a floor value of `1e-30` for
non-positive frequencies.
"""
function lisa_noise_psd(f)
    if f <= 0.0
        return 1e-30
    end
    p_oms = (1.5e-11)^2 * (1 + (2e-3/f)^4)
    p_acc = (3e-15)^2 * (1 + (0.4e-3/f)^2) * (1 + (f/8e-3)^4)
    s_inst =
        (p_oms / TelemetryCore.L_ARM^2) +
        (2 * p_acc / ((2π*f)^4 * TelemetryCore.L_ARM^2)) *
        (1 + cos(f/TelemetryCore.F_STAR)^2)
    # Galactic-binary confusion foreground (analytic fit): amplitude,
    # knee frequency [Hz], and shape parameters of the exponential cutoff.
    amp_gal, f_knee, alpha_gal, f_tanh, df_tanh =
        1.8e-44, 1.0e-4, 292.0, 10.0^(-3.5), 10.0^(-4.5)
    s_gal =
        amp_gal * f^(-7/3) * exp(-(f/f_knee)^alpha_gal) * (1 + tanh((f_tanh - f)/df_tanh))
    return s_inst + s_gal
end

"""
    next_segment!(vi::InstrumentState)

Produces the next temporal segment of science data. Automatically handles
chunking of external arrays or generation of synthetic noise. Synthetic
segments are phase-continuous across calls: each segment is the sum of the
previous block's overlap-add tail and the head of a freshly synthesized
windowed block (see [`InstrumentState`](@ref)).
"""
function next_segment!(vi::InstrumentState)
    n_samples = round(Int, vi.sample_rate * vi.seg_dur)

    if vi.use_external
        # Slice from external array
        end_idx = min(vi.ext_index + n_samples - 1, length(vi.ext_data))
        if vi.ext_index + n_samples - 1 > length(vi.ext_data)
            @warn "[INSTRUMENT] External data exhausted at segment $(vi.id_counter) " *
                  "(sample $(vi.ext_index) of $(length(vi.ext_data))): padding with zeros " *
                  "from here on. Provide a longer series or shorten the mission." maxlog = 1
        end
        if vi.ext_index > length(vi.ext_data)
            # Pad with zeros if we run out of external data
            data = zeros(Float32, n_samples)
        else
            data = vi.ext_data[vi.ext_index:end_idx]
            # Pad if slice is too short
            if length(data) < n_samples
                append!(data, zeros(Float32, n_samples - length(data)))
            end
        end
        vi.ext_index += n_samples
        is_sig = false # External data carries its own signal content; no injection.
    else
        block = synth_windowed_block(vi.rng, vi.noise_amp, vi.window)
        data = Float32.(vi.carry .+ view(block, 1:n_samples))
        vi.carry = block[(n_samples+1):end]
        # Stream-preserving form: rand > 1 - p reproduces the historical
        # realization exactly at the default p = 0.02.
        is_sig = rand(vi.rng) > 1.0 - vi.signal_injection_probability
    end

    seg = TelemetryCore.DataSegment(vi.id_counter, vi.last_t, data, is_sig)
    vi.last_t += Second(round(Int, vi.seg_dur))
    vi.id_counter += 1
    return seg
end

end # module VirtualInstrument
